version: "3.7"

services:
  database_plant_daddy:
    image: postgres
    container_name: database_plant_daddy
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=plantdaddy
      - POSTGRES_DB=plant_daddy
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: plant_daddy
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local